package:
  name: console_shortcut_anacondapro
  version: 0.1.1

build:
  number: 3
  skip: True # [not win]

requirements:
  run:
    - python

about:
  license: BSD
  summary: Console shortcut creator for Windows (using menuinst)

extra:
  recipe-maintainers:
    - bkreider
